import { useState } from 'react'
import { Plus, Search } from 'lucide-react'
import { useAgentReferrals, useCreateStudent } from '../../lib/api'

export default function AgentStudentsPage() {
  const [search, setSearch] = useState('')
  const [creating, setCreating] = useState(false)
  const { data = [], isLoading } = useAgentReferrals({ search })
  return <section className="mx-auto max-w-6xl rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Students</h1><p className="mt-1 text-sm text-slate-500">Your referred leads and students, together in one pipeline.</p></div><button onClick={() => setCreating(true)} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700"><Plus className="h-4 w-4" /> Create</button></div><div className="relative mt-5 max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, email or phone..." className="input w-full pl-9" aria-label="Search referred students" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="border-y border-slate-200 bg-brand-50/60 text-left text-sm font-semibold text-slate-700"><th className="px-4 py-3">Name</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Added On</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={4} className="px-4 py-12 text-center text-sm text-slate-500">Loading referrals...</td></tr> : data.map((row) => <tr key={`${row.type}-${row.id}`} className="border-b border-slate-100 text-sm"><td className="px-4 py-4 font-semibold text-slate-800">{row.name}<span className="ml-2 rounded-md bg-slate-100 px-2 py-1 text-xs font-medium text-slate-600">{row.type}</span></td><td className="px-4 py-4 text-slate-600">{row.email || '—'}<br /><span className="text-xs text-slate-500">{row.phone || '—'}</span></td><td className="px-4 py-4 text-slate-600">{row.status}</td><td className="px-4 py-4 text-slate-600">{row.addedOn}</td></tr>)}</tbody></table></div>{creating && <CreateReferral onClose={() => setCreating(false)} />}</section>
}

function CreateReferral({ onClose }: { onClose: () => void }) {
  const create = useCreateStudent(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState('')
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={(event) => { event.preventDefault(); create.mutate({ name, email, phone }, { onSuccess: onClose }) }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold text-slate-900">Create referral</h2><p className="mt-1 text-sm text-slate-500">A lead is created first and auto-converted according to your agent settings.</p><div className="mt-5 space-y-3">{[['Name', name, setName, true], ['Email', email, setEmail, false], ['Mobile', phone, setPhone, false]].map(([label, value, setter, required]) => <label key={label as string} className="block text-sm font-medium text-slate-600">{label as string}<input required={required as boolean} value={value as string} onChange={(e) => (setter as (value: string) => void)(e.target.value)} className="input mt-1 w-full" /></label>)}</div>{create.error && <p className="mt-3 text-sm text-rose-600">{create.error.message}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={create.isPending} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white">{create.isPending ? 'Saving...' : 'Create referral'}</button></div></form></div>
}