import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ChevronLeft, ChevronRight, Eye, Mail, MessageSquare, Plus, Search } from 'lucide-react'
import { useAgent, useAgents, useCreateAgent, useAgentSubmissionSetting, useUpdateAgent, useUpdateAgentSubmissionSetting, useBranches } from '../../lib/api'
import { cn } from '../../lib/cn'
import { ExportButtons } from '../../components/ExportButtons'
import { PageBtn } from '../../components/DataTableUI'

export default function AgentsPage() {
  const { id } = useParams()
  if (id) return <AgentDetail id={Number(id)} />
  return <AgentList />
}

function AgentList() {
  const { data: agents = [], isLoading } = useAgents()
  const { data: branches = [] } = useBranches()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [category, setCategory] = useState('')
  const [branch, setBranch] = useState('')
  const [pageSize, setPageSize] = useState(10)
  const [page, setPage] = useState(1)
  const [showCreate, setShowCreate] = useState(false)
  const query = search.trim().toLowerCase()
  const rows = agents.filter((agent) => (!query || `${agent.name} ${agent.company} ${agent.email}`.toLowerCase().includes(query)) && (!status || agent.status === status) && (!category || agent.category === category) && (!branch || agent.branchId === Number(branch)))
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize))
  const currentPage = Math.min(page, totalPages)
  const pageRows = rows.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const exportRows = rows.map((agent) => [agent.name, agent.company, agent.email, agent.phone, agent.category, agent.status, agent.commissionRate, agent.applications, agent.commissions])
  return (
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div><h1 className="text-xl font-bold text-slate-900">Agents</h1><p className="mt-1 text-sm text-slate-500">Manage partner agencies and referral relationships.</p></div>
        <button onClick={() => setShowCreate(true)} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700"><Plus className="h-4 w-4" /> Add Agent</button>
      </div>
      <div className="mt-5 grid gap-3 rounded-lg border border-slate-200 bg-slate-50/60 p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-medium text-slate-600">Status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }} className="input mt-1 w-full"><option value="">All statuses</option><option>Active</option><option>Inactive</option></select></label><label className="text-xs font-medium text-slate-600">Category<select value={category} onChange={(event) => { setCategory(event.target.value); setPage(1) }} className="input mt-1 w-full"><option value="">All categories</option><option>Small</option><option>Medium</option><option>Large</option></select></label><label className="text-xs font-medium text-slate-600">Branch<select value={branch} onChange={(event) => { setBranch(event.target.value); setPage(1) }} className="input mt-1 w-full"><option value="">All branches</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="flex items-end"><button onClick={() => { setStatus(''); setCategory(''); setBranch(''); setSearch(''); setPage(1) }} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">Clear filters</button></div></div>
      <div className="mt-4 flex flex-col gap-3 md:flex-row md:items-center"><label className="flex items-center gap-2 text-sm text-slate-600 md:flex-1">Show<select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1) }} className="input w-20 py-1.5"><option>10</option><option>50</option><option>100</option><option>500</option><option>1000</option></select>entries</label><div className="relative w-full max-w-md md:flex-[2]"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Search agents..." className="input w-full pl-9" aria-label="Search agents" /></div><ExportButtons title="Agents" filename="agents" header={['Name', 'Company', 'Email', 'Mobile', 'Category', 'Status', 'Commission %', 'Applications', 'Commissions']} rows={exportRows} onDone={() => {}} /></div>
      <SubmissionControl />
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="border-y border-slate-200 bg-brand-50/60 text-left text-sm font-semibold text-slate-700"><th className="px-4 py-3">Name</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Commission</th><th className="px-4 py-3">Referrals</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={7} className="px-4 py-12 text-center text-sm text-slate-500">Loading agents...</td></tr> : pageRows.map((agent) => <tr key={agent.id} className="border-b border-slate-100 text-sm"><td className="px-4 py-4"><Link to={`/agents/${agent.id}`} className="font-bold text-slate-800 hover:text-brand-600 hover:underline">{agent.name}</Link>{agent.company && <p className="text-xs text-slate-500">{agent.company}</p>}</td><td className="px-4 py-4"><a href={`mailto:${agent.email}`} className="flex items-center gap-1.5 text-slate-600 hover:text-brand-600"><Mail className="h-3.5 w-3.5" />{agent.email || '—'}</a><p className="mt-1 text-xs text-slate-500">{agent.phone || '—'}</p></td><td className="px-4 py-4 text-slate-600">{agent.category || '—'}</td><td className="px-4 py-4 font-semibold text-slate-700">{agent.commissionRate}%</td><td className="px-4 py-4 text-slate-600">{agent.applications} applications<br /><span className="text-xs">{agent.commissions} commissions</span></td><td className="px-4 py-4"><span className={cn('rounded-md px-2.5 py-1 text-xs font-semibold', agent.status === 'Active' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700')}>{agent.status}</span></td><td className="flex gap-1 px-4 py-4"><Link to={`/agents/${agent.id}`} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-2.5 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50" title="View agent"><Eye className="h-4 w-4" /></Link><a href={`mailto:${agent.email}`} className="inline-flex items-center rounded-lg border border-slate-300 px-2.5 py-2 text-slate-600 hover:bg-slate-50" title="Email agent"><Mail className="h-4 w-4" /></a><a href={`sms:${agent.phone}`} className="inline-flex items-center rounded-lg border border-slate-300 px-2.5 py-2 text-slate-600 hover:bg-slate-50" title="Message agent"><MessageSquare className="h-4 w-4" /></a></td></tr>)}{!isLoading && pageRows.length === 0 && <tr><td colSpan={7} className="px-4 py-12 text-center text-sm text-slate-500">No agents found.</td></tr>}</tbody></table></div>
      <div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-sm text-slate-500">Showing {rows.length ? (currentPage - 1) * pageSize + 1 : 0} to {Math.min(currentPage * pageSize, rows.length)} of {rows.length}</p><div className="flex items-center gap-1"><PageBtn onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={currentPage === 1}><ChevronLeft className="h-4 w-4" /></PageBtn><span className="px-2 text-sm text-slate-600">Page {currentPage} of {totalPages}</span><PageBtn onClick={() => setPage((value) => Math.min(totalPages, value + 1))} disabled={currentPage === totalPages}><ChevronRight className="h-4 w-4" /></PageBtn></div></div>
      {showCreate && <CreateAgent onClose={() => setShowCreate(false)} />}
    </section>
  )
}

function CreateAgent({ onClose }: { onClose: () => void }) {
  const create = useCreateAgent()
  const [form, setForm] = useState({ name: '', firstName: '', lastName: '', company: '', email: '', phone: '', country: '', state: '', city: '', address: '', category: '', rate: '', password: '', canSubmitApplications: false, autoConvertReferrals: false })
  const set = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  const fields = [['name', 'Name'], ['firstName', 'First name'], ['lastName', 'Last name'], ['company', 'Company'], ['email', 'Email'], ['phone', 'Mobile'], ['country', 'Country'], ['state', 'State'], ['city', 'City'], ['address', 'Address'], ['category', 'Category'], ['rate', 'Commission %'], ['password', 'Login password']] as const
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-900/40 p-4"><form onSubmit={(event) => { event.preventDefault(); create.mutate({ ...form, commissionRate: Number(form.rate) || 0, category: form.category || undefined }, { onSuccess: onClose }) }} className="my-8 w-full max-w-2xl rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold text-slate-900">Add agent</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([key, label]) => <label key={key} className="text-sm font-medium text-slate-600">{label}<input required={key === 'name'} type={key === 'password' ? 'password' : key === 'email' ? 'email' : 'text'} value={form[key]} onChange={(event) => set(key, event.target.value)} className="input mt-1 w-full" /></label>)}</div><div className="mt-4 space-y-3 border-t border-slate-100 pt-4"><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={form.canSubmitApplications} onChange={(event) => set('canSubmitApplications', event.target.checked)} /> Allow application submission</label><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={form.autoConvertReferrals} onChange={(event) => set('autoConvertReferrals', event.target.checked)} /> Auto-convert referrals</label></div>{create.error && <p className="mt-3 text-sm text-rose-600">{create.error.message}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={create.isPending} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{create.isPending ? 'Saving...' : 'Save agent'}</button></div></form></div>
}

function SubmissionControl() {
  const { data } = useAgentSubmissionSetting()
  const update = useUpdateAgentSubmissionSetting()
  return <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3"><div><p className="text-sm font-bold text-amber-900">Agent application submission</p><p className="text-xs text-amber-800">Global switch overrides each agent’s permission.</p></div><label className="flex items-center gap-2 text-sm font-semibold text-amber-900"><input type="checkbox" checked={data?.enabled ?? false} onChange={(event) => update.mutate(event.target.checked)} disabled={update.isPending} /> Enabled</label></div>
}

function AgentDetail({ id }: { id: number }) { const { data: agent, isLoading } = useAgent(id); const update = useUpdateAgent(); const navigate = useNavigate(); if (isLoading) return <p className="text-sm text-slate-500">Loading agent...</p>; if (!agent) return <p className="text-sm text-rose-600">Agent not found.</p>; return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><button onClick={() => navigate('/agents')} className="text-sm font-semibold text-brand-600 hover:underline">← Back to agents</button><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">{agent.name}</h1><p className="mt-1 text-sm text-slate-500">{agent.company || 'Independent partner'}</p></div><div className="flex items-center gap-3"><Link to={`/agents/${id}/edit`} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit</Link><span className="rounded-md bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-700">{agent.status}</span></div></div><dl className="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-slate-500">Email</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{agent.email || '—'}</dd></div><div><dt className="text-xs text-slate-500">Phone</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{agent.phone || '—'}</dd></div><div><dt className="text-xs text-slate-500">Commission rate</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{agent.commissionRate}%</dd></div><div><dt className="text-xs text-slate-500">Joined</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{agent.joined}</dd></div></dl><div className="mt-6 space-y-3 rounded-lg border border-slate-200 p-4"><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={agent.canSubmitApplications} onChange={(event) => update.mutate({ id, patch: { canSubmitApplications: event.target.checked } })} /> Allow application submission</label><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={agent.autoConvertReferrals} onChange={(event) => update.mutate({ id, patch: { autoConvertReferrals: event.target.checked } })} /> Auto-convert referrals</label></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Link to="/agents/referrals" className="rounded-lg border border-slate-200 p-4 hover:border-brand-300"><p className="text-xs text-slate-500">Applications</p><p className="mt-1 text-2xl font-bold text-slate-900">{agent.applications}</p></Link><Link to="/agents/invoices" className="rounded-lg border border-slate-200 p-4 hover:border-brand-300"><p className="text-xs text-slate-500">Commissions</p><p className="mt-1 text-2xl font-bold text-slate-900">{agent.commissions}</p></Link></div></section> }