import { randomUUID } from 'node:crypto'
import { createReadStream, existsSync } from 'node:fs'
import { mkdir, unlink, writeFile } from 'node:fs/promises'
import { extname, join, resolve, sep } from 'node:path'
import { Injectable } from '@nestjs/common'

/**
 * Where uploaded files physically live.
 *
 * Local disk for now. The method shape (put/get/remove keyed by an opaque
 * string) is the same one an S3-compatible client exposes, so swapping in
 * Cloudflare R2 later means implementing this class against the AWS SDK and
 * changing a provider binding — not touching any caller.
 */
@Injectable()
export class StorageService {
  /** Absolute, so a stray relative path cannot resolve outside the app. */
  private readonly root = resolve(process.env.UPLOAD_DIR ?? join(process.cwd(), 'uploads'))

  /**
   * Store bytes and return the opaque key used to fetch them back.
   *
   * The key is generated, never derived from the client-supplied filename:
   * that name is attacker-controlled and is the classic path-traversal vector
   * (`../../etc/passwd`). Only the extension is carried over, and only after
   * the caller has checked it against an allow-list.
   */
  async put(buffer: Buffer, originalName: string): Promise<string> {
    const ext = extname(originalName).toLowerCase().slice(0, 10)
    const key = `${randomUUID()}${ext}`
    await mkdir(this.root, { recursive: true })
    await writeFile(this.resolveKey(key), buffer)
    return key
  }

  /** A readable stream for a stored key, or null if the file is gone. */
  read(key: string) {
    const path = this.resolveKey(key)
    return existsSync(path) ? createReadStream(path) : null
  }

  /** Best-effort delete: a missing file is already in the desired state. */
  async remove(key: string): Promise<void> {
    try {
      await unlink(this.resolveKey(key))
    } catch {
      // Already gone, or never written — nothing to undo.
    }
  }

  /**
   * Map a key to a path inside the upload root, refusing anything that escapes
   * it. Keys are generated by `put`, so this should be unreachable — it is the
   * backstop for the day some caller passes a value straight from a request.
   */
  private resolveKey(key: string): string {
    const path = resolve(this.root, key)
    if (path !== this.root && !path.startsWith(this.root + sep)) {
      throw new Error('Resolved storage path escapes the upload root.')
    }
    return path
  }
}
